name: HelloServer

on:
  push:
    branches:
      - main

env:
  FILE_NAME: hello-server

jobs:
  build-go:
    name: Build Go
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Go code
      uses: actions/checkout@v2

    - name: Build ${{ env.FILE_NAME }} para ubuntu
      run: go build ${{ env.FILE_NAME }}.go

    - name: Build ${{ env.FILE_NAME }} para windows
      run: GOOS=windows GOARCH=amd64 go build ${{ env.FILE_NAME }}.go
      
    - name: Upload artefato para linux
      uses: actions/upload-artifact@v1.0.0
      with:
        name: linux
        path: ./${{ env.FILE_NAME }}

    - name: Upload artefato para Windows
      uses: actions/upload-artifact@v1.0.0
      with:
        name: windows
        path: ./${{ env.FILE_NAME }}.exe
