name: HelloServer

on:
  push:
    branches:
      - main
    schedule:
      - cron: "*/15 * * * 2-6"

env:
  FILE_NAME: hello-server

jobs:
  build-go:
    name: Build Go
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Codigo Go
      uses: actions/checkout@v2

    - name: Build ${{ env.FILE_NAME }} para ubuntu
      run: go build ${{ env.FILE_NAME }}.go

    - name: Build ${{ env.FILE_NAME }} para windows
      run: GOOS=windows GOARCH=amd64 go build ${{ env.FILE_NAME }}.go
      
    - name: Upload artefato para linux
      uses: actions/upload-artifact@v1.0.0
      with:
        name: linux
        path: ./${{ env.FILE_NAME }}

    - name: Upload artefato para Windows
      uses: actions/upload-artifact@v1.0.0
      with:
        name: windows
        path: ./${{ env.FILE_NAME }}.exe
  
  download-and-run-linux:
    name: Download-and-run-linux
    runs-on: ubuntu-latest
    needs: build-go
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: download Linux Artifact
        uses: actions/download-artifact@v4
        with:
          name: linux
      - name: Run Script
        run: source ./run.sh

  download-only-windows:
    name: Download Windows
    runs-on: windows-latest
    needs: build-go
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Download Windows Artifact
        uses: actions/download-artifact@v4
        with:
          name: windows
